(() => {
  const POS = ['QB','RB','WR','TE'];
  const DEPTH = {QB:1,RB:2,WR:3,TE:1};
  const val = p => Number(p?.dynasty_value_1qb || 0);
  const proj = p => Number(p?.projection || 0);
  const mine = () => myTeam();
  let tradeViewMode = 'overall';

  function floor(pos){const ps=(mine()?.players||[]).filter(p=>p.position===pos&&!p.reserve&&proj(p)>0).sort((a,b)=>proj(b)-proj(a));return proj(ps[Math.min((DEPTH[pos]||1)-1,Math.max(0,ps.length-1))]);}
  function gain(p){return Math.max(0,proj(p)-floor(p.position));}
  function positionCount(team,pos){return(team.players||[]).filter(p=>p.position===pos&&!p.reserve).length;}
  function marketCoverage(){const all=snapshot.teams.flatMap(t=>t.players||[]);const matched=all.filter(p=>val(p)>0).length;return{matched,total:all.length,pct:all.length?Math.round(matched/all.length*100):0};}
  function ownerNeed(team,pos){const count=positionCount(team,pos),target={QB:2,RB:5,WR:6,TE:2}[pos]||2;return Math.max(0,target-count);}
  function acquisition(target,partner){let score=58;const peers=(partner.players||[]).filter(p=>p.position===target.position&&String(p.player_id)!==String(target.player_id));const better=peers.filter(p=>val(p)>val(target)*.72).length;if(better>=2)score+=18;else if(better===1)score+=8;if(target.starter)score-=14;if(val(target)>=5000)score-=16;if(target.age&&target.age>=29)score+=8;if(ownerNeed(partner,target.position)>0)score-=12;return Math.max(10,Math.min(95,score));}
  function partnerNeeds(team){return POS.map(pos=>({pos,need:ownerNeed(team,pos)})).filter(x=>x.need>0).sort((a,b)=>b.need-a.need);}
  function expendableAssets(needs){const needSet=new Set(needs.map(x=>x.pos));return(mine()?.players||[]).filter(p=>POS.includes(p.position)&&val(p)>0&&!p.reserve).map(p=>({p,score:(p.starter?-20:15)+(needSet.has(p.position)?20:0)+Math.min(20,val(p)/300)})).sort((a,b)=>b.score-a.score||val(b.p)-val(a.p)).map(x=>x.p);}
  function offerFor(target,partner){const tv=val(target);if(!tv)return{text:'Use Analyze This Trade for a market-value package.',assets:[]};const assets=expendableAssets(partnerNeeds(partner)).filter(p=>String(p.player_id)!==String(target.player_id)&&val(p)<tv*1.25);let best=null;for(let i=0;i<assets.length;i++){const total=val(assets[i]);const d=Math.abs(total-tv*.82);if(!best||d<best.d)best={ps:[assets[i]],total,d};for(let j=i+1;j<Math.min(assets.length,12);j++){const t=total+val(assets[j]);const dd=Math.abs(t-tv*.88);if(!best||dd<best.d)best={ps:[assets[i],assets[j]],total:t,d:dd};}}if(!best)return{text:'Future draft capital or a depth package',assets:[]};const names=best.ps.map(p=>p.full_name).join(' + ');const gap=tv-best.total;let text=names;if(gap>900)text=`${names} + draft-value adjustment`;else if(best.total>tv*1.08)text=`${names} (ask for value back)`;return{text,assets:best.ps};}
  function tier(idea){if(idea.gain>=3&&idea.acq>=55&&idea.value<=5000)return['BUY','buy'];if(idea.gain>=2&&idea.acq>=62)return['VALUE TARGET','value'];if(idea.gain>=3&&idea.value>5000)return['EXPENSIVE BUT WORTH IT','expensive'];return['AVOID OVERPAY','avoid'];}
  function score(target,partner){const g=gain(target),v=val(target),acq=acquisition(target,partner);const ageBoost=target.age&&target.age<=26?6:0;const valueEfficiency=v?Math.max(-8,Math.min(14,(4500-v)/300)):0;return{gain:g,value:v,acq,score:Math.max(1,Math.min(99,Math.round(45+g*7+acq*.25+ageBoost+valueEfficiency)))};}
  function ideas(){const m=mine();if(!m)return[];const out=[];for(const partner of snapshot.teams.filter(t=>String(t.roster_id)!==String(m.roster_id))){for(const target of(partner.players||[])){if(!POS.includes(target.position)||target.reserve||proj(target)<=0)continue;const metrics=score(target,partner);if(metrics.gain<.75)continue;const idea={partner,target,...metrics};idea.tier=tier(idea);const offer=offerFor(target,partner);idea.offer=offer.text;idea.offerAssets=offer.assets;out.push(idea);}}return out.filter((x,i,a)=>a.findIndex(y=>String(y.target.player_id)===String(x.target.player_id))===i);}
  function reason(i){const parts=[];if(i.gain>=3)parts.push(`Projects to add about ${i.gain.toFixed(1)} points per week to your current lineup`);else parts.push(`Projects to add about ${i.gain.toFixed(1)} points per week to your current lineup`);if(i.value>=5000)parts.push('but carries cornerstone-level dynasty cost');else if(i.value>=2500)parts.push('with meaningful long-term market value');else parts.push('at a comparatively attainable dynasty price');if(i.acq>=65)parts.push('and the owner profile makes a deal relatively plausible');else if(i.acq<40)parts.push('though the current owner has limited incentive to sell');return parts.join(', ')+'.';}
  function myRosterImpact(i){const outgoing=i.offerAssets||[];if(!outgoing.length)return'The suggested framework relies on draft value or a custom package, so use Analyze This Trade to confirm what Boomtown can move without creating a new lineup hole.';const outgoingIds=new Set(outgoing.map(p=>String(p.player_id)));const roster=(mine()?.players||[]).filter(p=>POS.includes(p.position)&&!outgoingIds.has(String(p.player_id))&&!p.reserve);const positions=[...new Set(outgoing.map(p=>p.position))];const coverage=[];for(const pos of positions){const left=roster.filter(p=>p.position===pos).sort((a,b)=>proj(b)-proj(a));const names=left.slice(0,3).map(p=>`${p.full_name}${proj(p)>0?` (${proj(p).toFixed(1)} proj)`:''}`);if(names.length)coverage.push(`${pos} remains covered by ${names.join(', ')}`);else coverage.push(`${pos} would be thin after this offer`);}const outgoingStarter=outgoing.filter(p=>p.starter).map(p=>p.full_name);const targetPos=i.target.position;const targetContext=positions.includes(targetPos)?`${i.target.full_name} directly replaces production at ${targetPos}`:`${i.target.full_name} strengthens ${targetPos} while the outgoing positions retain the depth noted below`;const starterNote=outgoingStarter.length?`The package moves current starter${outgoingStarter.length>1?'s':''} ${outgoingStarter.join(' and ')}, so that replacement depth matters.`:`The suggested player package does not remove a current marked starter.`;return`${targetContext}. ${coverage.join('. ')}. ${starterNote}`;}
  function whyTheyMayListen(team){const needs=partnerNeeds(team);return needs.length?`${needs.slice(0,3).map(x=>x.pos).join(', ')} are their clearest roster needs.`:'Their roster has no obvious depth shortage, so a deal may require stronger value or a better positional fit.';}
  function tierTooltip(cls){if(cls==='buy')return'Strong weekly lineup improvement at a reasonable dynasty cost with a workable chance of getting the deal done. Based on projected points added, market cost and estimated trade likelihood.';if(cls==='value')return'Useful weekly lineup improvement with a favorable trade path relative to the market cost. Based on projected points added, market cost and estimated trade likelihood.';if(cls==='expensive')return'High dynasty cost, but the projected weekly scoring improvement is large enough to justify pursuing.';return'';}
  function tierBadge(label,cls){const tip=tierTooltip(cls);return tip?`<span class="trade-v2-tag ${cls}">${label}<span class="trade-v2-tooltip" tabindex="0" aria-label="${tip}" data-tooltip="${tip}">?</span></span>`:`<span class="trade-v2-tag ${cls}">${label}</span>`;}
  function acquisitionLabel(i){return i.acq>=65?'Favorable':i.acq>=45?'Possible':'Difficult';}
  function sortIdeas(all){const copy=[...all];if(tradeViewMode==='upgrade')return copy.sort((a,b)=>b.gain-a.gain||b.score-a.score||b.acq-a.acq);if(tradeViewMode==='attainable')return copy.sort((a,b)=>b.acq-a.acq||b.gain-a.gain||b.score-a.score);return copy.sort((a,b)=>b.score-a.score||b.gain-a.gain||b.acq-a.acq);}
  function viewCopy(){if(tradeViewMode==='upgrade')return['BIGGEST UPGRADES','Largest projected weekly scoring improvements to your current 2026 starting lineup.'];if(tradeViewMode==='attainable')return['MOST ATTAINABLE','Best combination of owner incentive to sell and a useful weekly scoring improvement.'];return['BEST OVERALL','Balances projected weekly improvement, market cost and likelihood of completing the trade.'];}
  function modeControls(){const [title,copy]=viewCopy();return`<section class="trade-v2-browser"><div><strong>${title}</strong><p>${copy}</p></div><div class="trade-v2-mode-tabs" role="tablist" aria-label="Trade target ranking"><button class="trade-v2-mode ${tradeViewMode==='overall'?'active':''}" data-mode="overall">BEST OVERALL</button><button class="trade-v2-mode ${tradeViewMode==='upgrade'?'active':''}" data-mode="upgrade">BIGGEST UPGRADES</button><button class="trade-v2-mode ${tradeViewMode==='attainable'?'active':''}" data-mode="attainable">MOST ATTAINABLE</button></div></section>`;}
  function card(i,n){const t=i.target,p=i.partner,[label,cls]=i.tier;return`<article class="panel trade-card trade-v2-card ${cls}"><div class="trade-v2-card-main"><div class="trade-v2-player"><div class="trade-v2-rank-row"><span class="trade-rank">#${n+1}</span>${tierBadge(label,cls)}</div><h3>${t.full_name}</h3><div class="player-meta">${[t.position,t.team,t.age?`Age ${t.age}`:null,t.injury_status].filter(Boolean).join(' &bull; ')}</div><div class="trade-owner"><span>OWNER</span><strong>${p.team_name||p.display_name||'Team'}</strong></div></div><div class="trade-v2-key-metrics"><div><span>WEEKLY LINEUP BOOST</span><strong class="positive">+${i.gain.toFixed(2)} pts</strong></div><div><span>TRADE LIKELIHOOD</span><strong>${acquisitionLabel(i)}</strong></div></div></div><div class="trade-v2-offer"><span>OPENING OFFER</span><strong>${i.offer}</strong></div><details class="trade-v2-details"><summary>Why this trade</summary><div class="trade-v2-details-body"><div class="trade-v2-why-block"><span class="trade-detail-label">WHY THE TARGET HELPS</span><p class="trade-v2-reason">${reason(i)}</p></div><div class="trade-v2-why-block"><span class="trade-detail-label">WHY BOOMTOWN CAN MAKE IT</span><p class="trade-v2-reason">${myRosterImpact(i)}</p></div><div class="trade-detail"><span class="trade-detail-label">WHY THEY MAY LISTEN</span><span>${whyTheyMayListen(p)}</span></div></div></details><button class="analyze-trade-btn" data-target="${t.player_id}" data-roster="${p.roster_id}">Analyze This Trade</button></article>`;}
  function renderV2(){if(!snapshot)return;let all=ideas();if(tradePosition!=='ALL')all=all.filter(i=>i.target.position===tradePosition);all=sortIdeas(all);const cov=marketCoverage(),top=all[0];$('boomtownTopNeed').textContent=top?.target.position||'Balanced';$('boomtownNeedDetail').textContent=top?`Best current upgrade opportunity | Market coverage ${cov.pct}%`:'No strong upgrade detected';$('bestTradePartner').textContent=top?.partner.team_name||'-';$('bestPartnerDetail').textContent=top?`Trade likelihood: ${acquisitionLabel(top)}`:'No strong match detected';$('topTradeTarget').textContent=top?.target.full_name||'-';$('topTargetDetail').textContent=top?`${top.tier[0]} | +${top.gain.toFixed(2)} projected points/week`:'No target detected';const grid=$('tradeRecommendations');const shown=all.slice(0,8);grid.innerHTML=all.length?`${modeControls()}<div class="trade-v2-count">Showing top ${shown.length} of ${all.length} matching targets</div><div class="trade-v2-grid">${shown.map(card).join('')}</div>`:'<article class="panel empty-trades">No trade targets matched the current filter.</article>';document.querySelectorAll('.trade-v2-mode').forEach(btn=>btn.onclick=()=>{tradeViewMode=btn.dataset.mode;renderV2();});document.querySelectorAll('.analyze-trade-btn').forEach(btn=>btn.onclick=()=>{const partner=snapshot.teams.find(t=>String(t.roster_id)===String(btn.dataset.roster));const target=partner?.players?.find(p=>String(p.player_id)===String(btn.dataset.target));const idea=all.find(x=>String(x.target.player_id)===String(btn.dataset.target));if(!partner||!target)return;launchAnalysis(`${tradePrompt(partner,target)}\n\nDashboard Trade Engine v2 context:\nDynasty market value: ${target.dynasty_value_1qb??'N/A'}\nDynasty ECR: ${target.dynasty_ecr_1qb??'N/A'}\nProjected weekly lineup improvement: ${idea?.gain?.toFixed(2)??'N/A'}\nInternal acquisition estimate: ${idea?.acq??'N/A'}\nSuggested opening framework: ${idea?.offer??'N/A'}\nBoomtown roster-impact reasoning: ${idea?myRosterImpact(idea):'N/A'}\n\nValidate the suggested package against current dynasty market conditions and tell me whether it is fair, an overpay, or an underpay. Also verify that Boomtown retains enough depth after the proposed outgoing players.`);});}
  renderTradeMarket=renderV2;
  const tradeBtn=$('analyzeTradesBtn');if(tradeBtn)tradeBtn.addEventListener('click',()=>setTimeout(renderV2,0));
  const filter=$('tradePositionFilter');if(filter)filter.addEventListener('change',()=>setTimeout(renderV2,0));
})();